name: Python Coverage Report with SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [curd_in_flash, folder2, folder3]  # your actual folders

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload coverage to SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_SCANNER_OPTS: "-Dsonar.projectKey=sumanbdev_lendingapp -Dsonar.organization=sumanbdev -Dsonar.python.coverage.reportPaths=${{ matrix.folder }}/coverage.xml"

    - name: Upload coverage artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.folder }}
        path: ${{ matrix.folder }}/coverage.xml
